language: python
python:
  - "3.6"

install: "pip install -r requirements.txt"

env:
  - DATABASE_URI=postgres://postgres:postgres@localhost:5432/testdb

before_script:
  - psql -c "create database testdb;" -U postgres

script:
  - nosetests

after_success:
  - codecov

services:
  - postgresql