language: python
python:
  - "3.6"

cache: pip
install: "pip install -r requirements.txt"

services:
  - postgresql

env:
  - TEST_DB_URI=postgres://postgres:postgres@localhost:5432/testdb

before_script:
  - psql -c "create database testdb;" -U postgres

script:
  - nosetests

after_success:
  - codecov
  - pylint --rcfile=pylint.conf service